In [3]:
import numpy as np

In [1]:
class LinearRegression:
    def __init__(self, lr = 0.001, n_iters=1000):
        self.lr = lr # how fast the model learns from the data 
        self.n_iters = n_iters # no of loops needed to learn from the data 
        self.weights = None # Weights: Think of the weights as how much attention the model gives to each piece of information in the data.
        self.bias = None # The bias term is like a baseline assumption the model starts with

    def fit(self, X, y):
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features) 
        self.bias = 0

        for _ in range(self.n_iters):
            y_pred = np.dot(X, self.weights) + self.bias # Performs matrix multiplication on X and self.weights


            # Gradient: The gradient of a function measures the rate of change of the function's value with respect to its parameters.
            dw = (1/n_samples) * np.dot(X.T, (y_pred-y))
            db = (1/n_samples) * np.sum(y_pred-y)

            self.weights = self.weights - self.lr * dw
            self.bias = self.bias - self.lr * db

    def predict(self, X):
        y_pred = np.dot(X, self.weights) + self.bias
        return y_pred
        

In [12]:
X = np.array([[1, 1], [1, 2], [1, 3]])
y = np.array([2, 3, 4])

In [13]:
X

array([[1, 1],
       [1, 2],
       [1, 3]])

In [14]:
X[:, 1:]

array([[1],
       [2],
       [3]])

In [29]:
model = LinearRegression(lr=0.01, n_iters=1000)# higher iter bettewr

In [23]:
model.fit(X, y)

In [27]:
y_pred = model.predict(X)

In [28]:
y_pred

array([1.99485687, 2.99903781, 4.00321874])