In [1]:
# NumPy is a multi dimensional array library used for numerical computing

# memory size

In [2]:
# 8 bits = 1 byte = 00000000
# 16 bits = 2 bytes = 00000000 00000000
# 32 bits = 4 bytes = 00000000 00000000 00000000 00000000

# Install NumPy

In [3]:
# pip install numpy

# Import NumPy

In [4]:
import numpy as np

# Initializing an array

## 1d

In [5]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

## 2d

In [6]:
b = np.array([[1,2,3], [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

## 3d

In [7]:
c = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10, 11, 12]]])
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## specify data type

In [15]:
a = np.array([1,2,3], dtype='int16')

# Visualization

## Get the dimension

In [8]:
a.ndim

1

In [9]:
b.ndim

2

In [10]:
c.ndim

3

## Get the shape

In [11]:
a.shape

(4,)

In [12]:
b.shape

(2, 3)

In [13]:
c.shape

(2, 2, 3)

## Get the data type and memory size

In [14]:
a.dtype

dtype('int32')

## Get the size in bytes

In [16]:
a.itemsize

2

## get the total elements

In [17]:
a.size

3

## Get the total no of bytes

### formula

In [18]:
a.size * a.itemsize

6

### command

In [19]:
a.nbytes

6

# Modifiying Elements

## Getting at a specific index

In [20]:
# a[r,c]

## getting a full row / column

### row

In [21]:
b[0, :]

array([1, 2, 3])

### column

In [22]:
b[:, 1]

array([2, 5])

## changing values

In [24]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
# changing 4 to 44
b[1,0] = 44

b

array([[ 1,  2,  3],
       [44,  5,  6]])

# Initializing Diff Types of Arrays

## All zeros

In [31]:
d = np.zeros((5,3))
d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## All ones

In [32]:
d = np.ones((3,3))
d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## All a specific number

In [33]:
d = np.full((3,3), 10)
d

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

### use shape of an already existing array

In [36]:
np.full_like(a,10)


array([10, 10, 10], dtype=int16)

In [37]:
np.full(a.shape, 10)

array([10, 10, 10])

## Generating Random Decimal

In [38]:
np.random.rand(2,2)

array([[0.10356392, 0.61088536],
       [0.72111861, 0.51614485]])

In [39]:
np.random.random_sample(a.shape)

array([0.22418586, 0.90908545, 0.03424359])

## Generating Identity Matrix

In [40]:
# i.e a square matrix with ones on the main diagonal and zeros else where
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## repeat an array

In [44]:
b

array([[ 1,  2,  3],
       [44,  5,  6]])

In [45]:
np.repeat(b, 3, axis=0)

array([[ 1,  2,  3],
       [ 1,  2,  3],
       [ 1,  2,  3],
       [44,  5,  6],
       [44,  5,  6],
       [44,  5,  6]])

In [46]:
np.repeat(b ,3, axis=1)

array([[ 1,  1,  1,  2,  2,  2,  3,  3,  3],
       [44, 44, 44,  5,  5,  5,  6,  6,  6]])

# Maths

## Basic Arithmetic

In [47]:
b + 2

array([[ 3,  4,  5],
       [46,  7,  8]])

## matric to matric

In [48]:
# excluding multiplications the shape must be the same

np.array([[1,2,3], [4,5,6]]) + np.array([[7,8,9], [10,11,12]])

array([[ 8, 10, 12],
       [14, 16, 18]])

# Linear Algebra

In [49]:
# A branch of maths concerning linear equations such as linear maps and their representations in vector spaces through matrices

In [50]:
# To multiply 2 matrices the column of the first one must be equal to the row of the second one

# i.e a(r1, c1) and b(r2, c2)
# c1 must be equal to r2

In [51]:
a1 = np.array([[1,2], [3,4]])

a2 = np.array([[5,6], [7,8]])

np.matmul(a1, a2)

array([[19, 22],
       [43, 50]])

## Determinant

In [53]:
a2

array([[5, 6],
       [7, 8]])

In [54]:
# the determinant is (5*8) - (6 * 7)

In [55]:
np.linalg.det(a2)

-1.999999999999999

# Statistics

## min value

In [57]:
b

array([[ 1,  2,  3],
       [44,  5,  6]])

In [58]:
np.min(b)

1

In [59]:
np.min(b, axis=1)

array([1, 5])

In [60]:
np.min(b, axis=0)

array([1, 2, 3])

## min value

In [61]:
np.max(b)

44

In [62]:
np.max(b, axis=1)

array([ 3, 44])

In [88]:
np.max(b, axis=0)

array([44,  5,  6])

## mean

In [89]:
np.mean(b)

10.166666666666666

## Standard Deviation

In [90]:
np.std(b)

15.225161922145707

## Percentile

In [91]:
np.percentile(b, 80)

6.0

## summing elements

In [64]:
np.sum(b)

61

In [66]:
np.sum(b, axis=0)

array([45,  7,  9])

# Reorganising Arrays

## Changing the shape

In [68]:
s = np.array([[1,2,3,4], [5,6,7,8]])
s.shape

(2, 4)

In [70]:
# the elements must fit (2*4)
s.size

8

In [72]:
# if we use 2,2,2 (2*2*2 = 8) so its a fit
s.reshape((2,2,2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

## Stacking

### Vertically

In [73]:
w = np.array([1,2,3,4])
r = np.array([5,6,7,8])

np.vstack([w,r])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### horizontally

In [74]:
np.hstack([w,r])

array([1, 2, 3, 4, 5, 6, 7, 8])

## Range

In [75]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [76]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Shuffle array

In [84]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [87]:
np.random.permutation(c)

array([[[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

# Working with Boolean

In [92]:
b > 2

array([[False, False,  True],
       [ True,  True,  True]])

In [94]:
# shows only true
b[b>2]

array([ 3, 44,  5,  6])

## check if atleast one is true

In [95]:

np.any(b>2)

True

In [96]:
# column by culumn
np.any(b>2, axis=0)

array([ True,  True,  True])

In [97]:
# row by row
np.any(b>2, axis=1)

array([ True,  True])

## check if everything is true

In [98]:

np.all(b>2)

False

In [99]:
# column by culumn
np.all(b>2, axis=0)

array([False, False,  True])